'use client'

import { Inter } from 'next/font/google'
import { ApolloProvider } from '@ufopark/network/src/config/apollo'
import '@ufopark/ui/src/app/globals.css'
import { SessionProvider } from '@ufopark/ui/src/components/molecules/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body className={inter.className}>{children}</body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  )
}
